# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAuthor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(390, 140, 101, 41))
        self.btnClose.setObjectName("btnClose")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 561, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#0000FF")
        self.label_2.setObjectName("label_2")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(170, 140, 101, 41))
        self.btnAdd.setObjectName("btnAdd")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 100, 501, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tw_author = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_author.setGeometry(QtCore.QRect(10, 190, 631, 321))
        self.tw_author.setObjectName("tw_author")
        self.tw_author.setColumnCount(3)
        self.tw_author.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author.setHorizontalHeaderItem(2, item)
        self.tw_author.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnClose.setText(_translate("MainWindow", "返回"))
        self.label_2.setText(_translate("MainWindow", "链接格式：\n"
"1.https://www.kuaishou.com/profile/3xsj4bm964dk5ug\n"
"2.3xsj4bm964dk5ug"))
        self.btnAdd.setText(_translate("MainWindow", "添加"))
        self.lineEdit.setText(_translate("MainWindow", "https://www.kuaishou.com/profile/3xsj4bm964dk5ug"))
        self.label.setText(_translate("MainWindow", "作品主页："))
        item = self.tw_author.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "作者ID"))
        item = self.tw_author.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者昵称"))
        item = self.tw_author.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最后保存时间"))
