# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewDataManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataManagement(object):
    def setupUi(self, DataManagement):
        DataManagement.setObjectName("DataManagement")
        DataManagement.resize(940, 566)
        DataManagement.setStyleSheet("font: 15px \"Ryanの阿里媽媽方圓體100\";")
        self.centralwidget = QtWidgets.QWidget(DataManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.tw_author = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_author.setGeometry(QtCore.QRect(20, 70, 400, 471))
        self.tw_author.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_author.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_author.setObjectName("tw_author")
        self.tw_author.setColumnCount(2)
        self.tw_author.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author.setHorizontalHeaderItem(1, item)
        self.tw_author.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Ryanの阿里媽媽方圓體100")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 40, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Ryanの阿里媽媽方圓體100")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(820, 10, 101, 41))
        self.btnClose.setObjectName("btnClose")
        self.tw_author_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_author_2.setGeometry(QtCore.QRect(520, 70, 400, 471))
        self.tw_author_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_author_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_author_2.setObjectName("tw_author_2")
        self.tw_author_2.setColumnCount(2)
        self.tw_author_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_author_2.setHorizontalHeaderItem(1, item)
        self.tw_author_2.verticalHeader().setVisible(False)
        self.btnClose_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose_2.setGeometry(QtCore.QRect(430, 230, 80, 30))
        self.btnClose_2.setObjectName("btnClose_2")
        self.btnClose_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose_3.setGeometry(QtCore.QRect(430, 290, 80, 30))
        self.btnClose_3.setObjectName("btnClose_3")
        DataManagement.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataManagement)
        QtCore.QMetaObject.connectSlotsByName(DataManagement)

    def retranslateUi(self, DataManagement):
        _translate = QtCore.QCoreApplication.translate
        DataManagement.setWindowTitle(_translate("DataManagement", "采集信息管理"))
        item = self.tw_author.horizontalHeaderItem(0)
        item.setText(_translate("DataManagement", "作者昵称"))
        item = self.tw_author.horizontalHeaderItem(1)
        item.setText(_translate("DataManagement", "最后保存时间"))
        self.label_2.setText(_translate("DataManagement", "采集的作者信息"))
        self.label_3.setText(_translate("DataManagement", "不采集的作者信息"))
        self.btnClose.setText(_translate("DataManagement", "返回"))
        item = self.tw_author_2.horizontalHeaderItem(0)
        item.setText(_translate("DataManagement", "作者昵称"))
        item = self.tw_author_2.horizontalHeaderItem(1)
        item.setText(_translate("DataManagement", "最后保存时间"))
        self.btnClose_2.setText(_translate("DataManagement", "<<"))
        self.btnClose_3.setText(_translate("DataManagement", ">>"))
